### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by wwevo** [wwevo/guildhome#66]
As the events and shouts amass, we enter a stage where we need pagination.

Should this be done in pages? or in this new fashion where the list gets longer the further you scroll down? should old stuff simply be archived and disappear from the standard view? or even deleted?

**Comment by Kakirtog** [comment]
I think pagination (if it is the thing where you get 10 pages of something instead of a loooong list of posts) is a good idea. As long as we have the space on the database, it shouldn't delete stuff.

**Comment by AniOnGit** [comment]
I vote for pagination as well for the simple fact that yes, scrolling down and content lazy loaded when I scroll is cool, but: You won't see anything else of the site anymore. Using the menu or something would - depending on how far I scroll ;) - get totally out of reach. That's why I like pagination more.

**Comment by wwevo** [comment]
Most basic pagination implemented. this needs to be beautified of course. But this ticket is closed ^^ open up new ones for bugs and beauty-tips :)
