### ISSUE TITLE
What people want out of the website

### ISSUE THREAD

**Issue by Kakirtog** [wwevo/guildhome#78]
I've taken the liberty of asking in guildchat what people would like to see from the website tonight (I did this because it might be hard for people to be honest and critical to the people building that website) and got some interesting answers. Don't get me wrong, I don;t want to hijack the project, but we need the iinput of the users if we want it to be used.

Here's the ideas that were suggested:

1. A calendar view for events - It seems that for the website to be clearer, people want a calendar on which you can see when events are happening. Ari suggested using a Google calendar plugin, that can show these, and also offer to directly import them to your personal calendar. My idea is to have about a month into the future visible, and to put it on the Activity/Events pages, on the side underneath the profile stuff.

2. A separate page for special events (also the possibility to set up special events I guess) - Special events like Find my location or Guild hall treasure hunt don;t have a place atm. I think these would pull a lot of activity to the website. However, they can;t be set up as normal events (as there is no date), and if they're run as shouts or announcements it will clog up the rest of the website. Necro suggested a separate page for an overview of these. I think they should basically be shouts that have their own page instead of being actual shouts (if you get what I mean). Also, we need to be able to put up pictures for this (maybe that should have been a separate point?).

3. A TS3 plugin/link - Ari suggested a TS3 link where you click on it and it opens TS3 with the channel data and password loaded, so you don't have to type anything. I think that's a bit sparse on usefulness, since you really only have to type it once, and then bookmark it, but maybe it has a use, I guess it won;t take up much space (though I'm not sure where we should put that). I did have another idea about TS functionality, and that's a plugin which shows the server state, specifically whether someone is in a channel. That way you can see if there's someone to talk to, and you get a bit more use out of a TS thing. Ari commented that that was maybe not necessary with our server population, where he has a point.

That's mostly it, I'll comment on this if I get more suggestions, I'll also ask a couple more times in guildchat.

**Comment by wwevo** [comment]
Quite a lot to read ^^

1. Since I have never used a calendar and never even looked at the google one, I have to admit that I am not able to integrate anything mentioned in the first suggestion. I can set up a calendar view where one month is shown and all events are marked, that's about it :) So a small calendar widget should be no problem, it would then replace the list of upcoming events I suppose.

I have been thinking about our much loved special events as well, especially find my location. With the new maps and content it's even more of a challenge. A 'Special Event Activity' with it's own landing page sounds sensible to me, for most of them it would just be like a fancy shout with fancy comments. They could get something like a 'sticky' posted on top of the stream. Perhaps even just small icons showing that any of those special events is currently active?

Perhaps there could be an entire area above the stream reserved for current stuff? Pulled events might get a compact view, perhaps several of them next to each other instead of simply being on top of the stream with a box like it is now.

```
Header
------------
activity_menu
-----------
current stuff, not bigger in area than the activity_menu above it
-----------
activity stream
-----------
Footer
```

Btw, you can put up pictures, you just can't load them up to our server. You can however embed any directly linked image (imgur, tinypic etc.) into any shout/event/comment textarea. It should be a simple matter to make that easier to access using a button that opens a dialogue for the picture url. Uploading images is on the to-do list though, I was starting to think about installing a simple image-hosting site @ images.notjustfor.me. 

Well, for logged in users, who need to have that special voucher, we could simply put that TS3 link in the sidebar. How is such a link constructed? Implementing a ts3 status should also pose no problem since it runs on the same server.

Best thing would be to open new issues for each of these suggestions, so we can discuss them and tick them off one by one :)
