### ISSUE TITLE
Event deleted message

### ISSUE THREAD

**Issue by AniOnGit** [wwevo/guildhome#82]
When an event got deleted it's comments site is still reachable/visible. That is good! But now instead of the event description there is just a nothing and then comments.
It would be great if we could have a 'event got deleted' message there to make it absolutely clear what happened there :)

**Comment by wwevo** [comment]
Got the original event (also shout) crossed out now with functions disabled. I believe this is a good solution as people who delete events (shouts) would otherwise also delete all added comments.
I feel this feature can be considered implemented. Please open additional Issues for bugs, if you find any and also for feature requests, if you have any ^^
